name: ssi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 本地存储、收藏功能
  shared_preferences: ^0.5.3
  share: ^0.6.2
  # http请求
  dio: ^3.0.2
  event_bus: ^1.1.0
  # 路由管理
  fluro: "^1.5.1"
  # sqlite库操作
  sqflite: ^1.1.6
  # 通过url打开本地应用，如短信，浏览器等
  url_launcher: ^5.1.4
  # 打开webview
  # flutter_webview_plugin: ^0.3.8
  # 三级城市选择
  city_pickers: ^0.1.27
  # This package defines annotations that can be used by the tools that are shipped with the Dart SDK.
  meta: ^1.1.7
  # 路径工具类
  path_provider: ^1.3.0
  # 权限检查：https://pub.dev/packages/permission_handler
  permission_handler: ^3.2.2
  # 打开本地文件：https://pub.dev/packages/open_file
  open_file: ^2.0.3
  # 安装包查询
  package_info: ^0.4.0+6
  # flutter_pulltorefresh a widget provided to the flutter scroll component drop-down refresh and pull up load.support android and ios
  pull_to_refresh: ^1.5.6
  # 极光推送
  flutter_jpush: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ss.db
    - assets/images/
    - assets/fonts/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

